#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainPanel;
                ref class StackPanel;
                ref class TextBox;
                ref class ComboBox;
                ref class Slider;
            }
        }
    }
}

namespace Converter
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class MainPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ m_swapChainPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ m_menuPanel;
        private: ::Windows::UI::Xaml::Controls::TextBox^ m_filenameTextBox;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ m_materialList;
        private: ::Windows::UI::Xaml::Controls::TextBox^ m_textureTextBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ m_normalmapTextBox;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_colorWeightSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_redSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_greenSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_blueSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_alphaSlider;
    };
}

