#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainPanel;
                ref class StackPanel;
                ref class ComboBox;
                ref class TextBox;
                ref class Slider;
                ref class CheckBox;
            }
        }
    }
}

namespace Converter
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class MainPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ m_swapChainPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ m_menuPanel;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ m_modelList;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ m_materialList;
        private: ::Windows::UI::Xaml::Controls::TextBox^ m_textureTextBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ m_normalmapTextBox;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_specularPowerSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_specularRedSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_specularGreenSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_specularBlueSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_specularAlphaSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_textureWeightSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_diffuseRedSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_diffuseGreenSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_diffuseBlueSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_diffuseAlphaSlider;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ m_modelShownCheckBox;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ m_bonePanel;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ m_boneList;
        private: ::Windows::UI::Xaml::Controls::TextBox^ m_toBoneTxTextBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ m_toBoneTyTextBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ m_toBoneTzTextBox;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_toBoneRxSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_toBoneRySlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_toBoneRzSlider;
        private: ::Windows::UI::Xaml::Controls::TextBox^ m_transformTxTextBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ m_transformTyTextBox;
        private: ::Windows::UI::Xaml::Controls::TextBox^ m_transformTzTextBox;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_transformRxSlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_transformRySlider;
        private: ::Windows::UI::Xaml::Controls::Slider^ m_transformRzSlider;
    };
}

